pipeline {
    agent {
        label 'slave1'
    }

    tools {
         maven 'maven1'
    }

    stages {
        stage('build stage') {
            steps {
                sh "mvn clean package"
            }

            post {
                success {
                  archiveArtifacts artifacts: '**/target/*.war'  
                 }
            }
        }

    }
}
