pipeline {
    agent {
        label 'slave1'
    }

    tools {
         maven 'maven1'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
                sh 'ls -l target/' // Debugging step
            }
        }
        stage('Archive') {
            steps {
                echo "Archiving artifacts"
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }
}
