pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "build stage"
              //  sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo "test stage"
              //  sh 'mvn test'
            }
           /* post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }*/
        }
        stage('Deliver') {
            steps {
                echo "deployment stage"
               // sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
